const speakers = [
  {
    id: 1,
    name: "Len Pierre",
    slug: "len",
    videoReady: true,
    img: "/images/speakers/len.jpg",
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/len@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/len.srt",
    talkTitle: "Cultural Safety Education as the BluePrint for Reconciliation",
    bio: "Coast Salish consultant and cultural knowledge keeper",
    description: "Len Pierre is a Coast Salish consultant and cultural knowledge keeper specialized in decolonization, reconciliation, development of educational programs, and Indigenization. To him, Bloom means re-birth and a fresh outlook!",
  },
  {
    id: 2,
    name: "Candida Moreira",
    slug: "candida",
    img: "/images/speakers/candida.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle: "Once upon a(nother) time: a different kinda love story",
    bio: "Relational trauma therapist and writer",
    description: "Candida Moreira is a relational trauma therapist & writer who thrives at the intersection of language and feelings. She is passionate about smashing stigmas and encouraging folx to move through the world fully owning all of who they are. She has a knack for complicating things, colouring outside the lines, & taking the scenic route.",
  },
  {
    id: 3,
    name: "Lisa Bournelis",
    slug: "lisa",
    img: "/images/speakers/lisa.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle: "3 Questions to Change Your Life",
    bio: "Transformation leader for one of Canada’s largest health authorities",
    description: "Lisa Bournelis is a transformation leader for one of Canada’s largest health authorities. She is also a new author, blogger, podcaster, mom, taekwondo black belt, and former humanitarian aid worker. For her, Bloom represents the growth after a period of challenge that creates a new individual, mindset, skillset and spirit.",
  },
  {
    id: 4,
    name: "Matthew Provost",
    slug: "matthew",
    img: "/images/speakers/matt.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle: "Unpacking the Indigenous Student Experience",
    bio: "Curent undergraduate student at SFU",
    description: "demo description",
  },
  {
    id: 5,
    name: "Dinara Mukhametianova",
    slug: "dinara",
    img: "/images/speakers/dinara.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle: "Your Menstrual Cycle is Your Superpower",
    bio: "Certified Health Coach",
    description: "demo description",
  },
  {
    id: 6,
    name: "Robert Woodbury",
    slug: "robert",
    img: "/images/speakers/robert.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle: "Choices and Options",
    bio: "Retired professor of computational design",
    description: "demo description",
  },
  {
    id: 7,
    name: "Alexandra Kitson",
    slug: "alexandra",
    img: "/images/speakers/alexandra.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle:
      "Virtual reality: supporting our mental health through emotion regulation skills training",
    bio: "Post Doctoral Fellow at SFU SIAT",
    description: "demo description",
  },
  {
    id: 8,
    name: "Carissa Campeotto",
    slug: "carissa",
    img: "/images/speakers/carissa.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle: "How I found my bloom in a world that grows garbage",
    bio: "Social Entrepreneur",
    description: "demo description",
  },
  /*{
    id: 9,
    name: "Noor Fadel",
    slug: "noor",
    img: "/images/speakers/noor.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle: "Healing beyond the headlines",
    bio: "Award-winning educator, spoken word poet, and public speaker",
  },*/
  {
    id: 9,
    name: "Mariah-Jane Thies",
    slug: "mariah-jane",
    img: "/images/speakers/mariah-jane.jpg",
    videoReady: false,
    videoSrc: "https://www.sfu.ca/~kkl64/tedxsfu/candida@1920.mp4",
    subtitleSrc: "https://www.sfu.ca/~kkl64/tedxsfu/captions/candida.srt",
    talkTitle: "Moving from Surviving to Thriving",
    bio: "Dance and movement educator",
    description: "demo description",
  },
];

module.exports = speakers;
