//@ts-check
const sponsors = {
    platinum: [
        {
            name: "SFU External Relations",
            logo: "/images/sponsors/sfu-external-relations.png",
            about: "As a primary link between SFU and our communities, SFU External Relations pursues a comprehensive approach to the advancement of institutional priorities and promotes SFU’s reputation as the leading engaged university defined by its dynamic integration of innovative education, cutting-edge research, and far-reaching community engagement.",
            website:
                "https://www.sfu.ca/vpexternal/vice-president-external-relations.html",
            facebook: "https://www.facebook.com/simonfraseruniversity/",
            instagram: "https://www.instagram.com/simonfraseru/",
            twitter: "https://twitter.com/SFU",
            linkedIn:
                "https://www.linkedin.com/school/simon-fraser-university/mycompany/",
        },
        {
            name: "SFU Beedie School of Business",
            logo: "/images/sponsors/sfu-beedie.png",
            about: "Simon Fraser University’s Beedie School of Business is home to those who believe in the power of business to spark new ideas, fuel social innovations, and advance society. Operating across the three campuses in the major cities of Burnaby, Surrey and Vancouver, SFU Beedie is creating the business leaders of tomorrow through management educations programs for both undergraduate and graduate students through teaching and learning powered by world-class research, meaningful community engagement, and a global outlook. SFU Beedie takes business education beyond the walls of academia and empowers people from diverse backgrounds and perspectives to reimagine the role of business in tackling society’s most significant challenges.",
            website: "https://beedie.sfu.ca/",
            facebook: "https://www.facebook.com/SFUBeedie/",
            instagram: "https://www.instagram.com/sfubeedie/",
            twitter: "https://twitter.com/SFUBeedie",
            linkedIn: "https://www.linkedin.com/school/sfubeedie/",
        },
    ],
    gold: [
        {
            name: "SFU Alumni Association",
            logo: "/images/sponsors/sfu-alumni.png",
            about: "The SFU Alumni Association was founded in 1969 and has a membership of more than 165,000 grads around the world. We’re proud that more than 170,000 people have graduated from SFU! We are committed to keeping alumni informed, involved, and invested in the alumni community.",
            website: "http://www.sfu.ca/alumni.html",
            facebook: "https://www.facebook.com/sfualumni/",
            instagram: "https://www.instagram.com/sfualumni_",
            twitter: "https://twitter.com/sfualumni",
            linkedIn:
                "https://www.linkedin.com/showcase/sfu-advancement-and-alumni-engagement/",
        },
    ],
    silver: [
        {
            name: "BMO SFU Mastercard",
            logo: "/images/sponsors/bmo-sfu.png",
            about: "Support your alma mater with the BMO StFX Mastercard.  Every time you make a purchase, BMO makes a contribution to the StFX Alumni Association at no additional cost to you.  It’s an easy way to show your school pride and earn rewards at the same time.",
            website: "http://www.bmo.com/sfu",
            facebook: "https://www.facebook.com/BMOcommunity",
            instagram: "https://www.instagram.com/BMOCanada",
            twitter: "https://twitter.com/BMO",
            linkedIn:
                "https://www.linkedin.com/company/bank-of-montreal/life/b0ba8158-8cd9-4209-9f9d-a3b361584a9a/",
        },
        {
            name: "G&F Financial Group",
            logo: "/images/sponsors/gf.png",
            about: "With over 52,000 members, 24 locations and $4 billion in total assets under administration, G&F Financial Group proudly provides a full range of personal and business banking, investment and insurance solutions to our credit union members. With a passion for educating and empowering others to achieve their financial goals, we focus on providing advice tailored uniquely for each member and have supported members and invested in our local communities for 80 years.",
            website: "https://www.gffg.com",
            facebook: "https://www.facebook.com/GFFGcu",
            instagram: "https://www.instagram.com/gffgcu/",
            twitter: "https://twitter.com/gffg",
        },
        {
            name: "Office of the Vice President, Research and International",
            logo: "/images/sponsors/sfu-research-and-international.jpg",
            about: "Simon Fraser University's Office of the Vice-President, Research and International (VPRI) serves to encourage, facilitate, administer and promote research at SFU—nationally and internationally. We advocate and support university research, while guiding policy development at academic and government levels. As Canada’s Engaged University, we support SFU researchers as they translate their discoveries into real-world impact. Research at SFU spans eight faculties covering a broad range of fundamental, interdisciplinary and applied research topics, as outlined in our Strategic Research Plan. Our faculty members collaborate with researchers across Canada and in more than 125 countries around the world.",
            website: "https://www.sfu.ca/research",
            facebook: "https://www.facebook.com/SFUResearch",
            twitter: "https://twitter.com/SFUResearch",
            linkedIn: "https://www.linkedin.com/school/simon-fraser-university",
        },
    ],
    city: [
        {
            name: "City of New Westminster",
            logo: "/images/sponsors/new-west.png",
            about: "The City Partnership Grant Program is designed to assist not-for-profit incorporated organizations with delivery of major services to the community. To provide organizations with funding certainty, the City Partnership Grant will be for a term of one to three years at Council’s discretion. All recipients of City Partnership Grants will be required to submit a Statement of Accountability by December 31st of each year of the award. Applicants awarded multi-year grant terms are not required to submit applications in subsequent years provided the City has received and accepted their annual Statement of Accountability from the previous year in the prescribed format. The services must assist the city to fulfill the City Partnership Grant objectives.",
            website: "https://www.newwestcity.ca",
        },
    ],
    avSponsors: [
        {
            name: "McMedia Audio Visual Services",
            logo: "/images/sponsors/mc-media.png",
            about: "Team McMedia is AV and so much more! Audio Visual Sales, Installations, Rentals, Design, Content, Project and Event Management. Have a project? We can help!",
            website: "https://mcmedia-av.ca",
            facebook: "https://www.facebook.com/McMediaAV/",
            instagram: "https://www.instagram.com/mcmediaav/",
        },
    ],
    inkind: [
        {
            name: "Dead Frog Brewery",
            logo: "/images/sponsors/dead-frong-brewery.png",
            about: "Dead Frog is a locally owned, award-winning craft brewery born and raised in the Fraser Valley with 20+ craft brews on tap, fresh eats, and good times. They feature creative brews and unique eats that make you want to come back for more!",
            website: "http://deadfrog.ca/",
            facebook: "https://www.facebook.com/deadfrogbrewery",
            instagram: "https://www.instagram.com/deadfrogbrewery/",
            twitter: "https://twitter.com/DeadFrogBrewery",
        },
        {
            name: "Grounds for Coffee",
            logo: "/images/sponsors/grounds-for-coffee.png",
            about: "Thank you and shout out to @GroundsYVR for providing these #NiceBuns for our event. Grounds for Coffee has been home to the world's best cinnamon bun since 1993, with locations at Alma & 10th and on The Drive.",
            website: "http://groundsforcoffee.ca/",
            instagram: "https://www.instagram.com/groundsyvr/",
            twitter: "https://twitter.com/GroundsYVR",
        },
        {
            name: "Catoro Cafe",
            logo: "/images/sponsors/catoro-cafe.png",
            about: "Catoro Cafe is an institution in the community to promote animal welfare, mental wellness, and climate control by means of waste recycling. Catoro consistently engages with the community by offering programs that support local artists, people with mental illness, students, and many more.",
            website: "http://www.catoropets.com/",
            facebook: "https://www.facebook.com/catoropets",
            instagram: "https://www.instagram.com/catoropets/",
            twitter: "https://www.tiktok.com/@catorocafe?lang=en",
        },
        {
            name: "VNYSA",
            logo: "/images/sponsors/vnysa.png",
            about: "Use promo code: TEDXSFU to receive your first 2 months subscription at 50% off (regular price $9.99 USD / month).",
            website: "https://www.vnysa.com/",
            facebook: "https://www.facebook.com/vnysastudio",
            instagram: "https://www.instagram.com/vnysastudio/",
        },
        {
            name: "Steve’s Poke Bar",
            logo: "/images/sponsors/steves.png",
            about: "Steve's Poké Bar is grateful to their amazing loyal customers who supported them throughout the pandemic and are proud to be sponsoring groups and community events such as this.",
            website: "http://www.stevespokebar.ca/",
            facebook: "https://www.facebook.com/stevespokebar",
            instagram: "https://www.instagram.com/stevespokebar/",
        },
        {
            name: "Modo Yoga Vancouver",
            logo: "/images/sponsors/modo-yoga-vancouver.png",
            about: "The Modo Yoga Vancouver community is joined together by a love of yoga, commitment to protecting the earth, and of course a passion for long walks on the beach. They offer accessible classes that are challenging, healthy, and fun!",
            website: "http://modoyogavancouver.com/",
            facebook: "https://www.facebook.com/modoyogavancouver",
            instagram: "https://www.instagram.com/modoyogavancouver/",
        },
        {
            name: "Red Truck Beer Company",
            logo: "/images/sponsors/red-truck-beer-company.png",
            about: "Red Truck Beer is built on the values of a simpler time, when you didn’t need a dictionary to order a drink when trucks went to work, not the mall. That’s why they keep their beer simple and brew it honestly and independently, with no preservatives, pasteurization, or shortcuts.",
            website: "https://redtruckbeer.com/",
            facebook: "https://www.facebook.com/RedTruckBeer/",
            instagram: "https://www.instagram.com/redtruckbeer/",
            twitter: "https://twitter.com/redtruckbeer",
        },
        {
            name: "Skoah",
            logo: "/images/sponsors/skoah.jpg",
            about: "Skoah is a Vancouver-based skin care product company with locations in Canada and the US. Since 2001 skoah has earned recognition in many well-respected publications including Style, The New York Times, Allure, The Global and Mail, Travel and Leisure, Women’s Wear Daily and Vogue.",
            website: "https://www.skoah.com/",
            facebook: "https://www.facebook.com/skoah",
            instagram: "https://www.instagram.com/skoah/",
            twitter: "https://twitter.com/skoah",
        },
        {
            name: "Nelson the Seagull",
            logo: "/images/sponsors/nelson-the-seagull.png",
            about: "Nelson the Seagull is a family-run cafe + sourdough bakery with South African roots. We’re located in historic Gastown and opened our doors in 2011. We just celebrated 10 years! Our brunch + lunch menu is built around our various freshly baked sourdough breads and our drinks are made using locally roasted coffee.",
            website: "https://www.nelsontheseagull.com/",
            facebook: "https://www.facebook.com/nelsontheseagull",
            instagram: "https://www.instagram.com/nelsontheseagull/",
            twitter: "https://twitter.com/gastownseagull",
        },
        {
            name: "Everything Wine",
            logo: "/images/sponsors/everything-wine.png",
            about: "Check out their website to learn more.",
            website: "https://www.everythingwine.ca/",
            facebook: "https://www.facebook.com/EverythingWineInc",
            instagram: "https://www.instagram.com/ewinebc/",
            twitter: "https://twitter.com/EWineBC",
        },
        {
            name: "Steamworks Brewery",
            logo: "/images/sponsors/steamworks.png",
            about: "For over 25 years, Steamworks Brewing Co. has been at the forefront of craft brewing, innovation and taste. Named after the central steam system that powers its Gastown brewhouse and world-famous steam clock in Vancouver B.C., Steamworks proudly brews distinct, delicious, and award-winning craft beers. For more information, visit us at https://steamworks.com/",
            website: "https://steamworks.com/",
            facebook: "https://www.facebook.com/SteamworksBeer",
            instagram: "https://www.instagram.com/steamworksbeer/",
            twitter: "https://twitter.com/steamworksbeer",
        },
        {
            name: "Old Spaghetti Factory",
            logo: "/images/sponsors/spaghetti-factory.png",
            about: "Check out their website to learn more.",
            website: "https://oldspaghettifactory.ca/",
            facebook: "https://www.facebook.com/osfgastown",
            instagram: "https://www.instagram.com/oldspaghettifactory_gastown/",
        },
        {
            name: "FlyOverCanada",
            logo: "/images/sponsors/FlyOver_Canada.webp",
            about: "Soar across some of Canada’s most spectacular scenery and natural wonders with the latest in simulated flight technology. Wind, scents and other amazing effects will give the true feeling of flight. The complete experience is approximately 25 minutes, encompassing three different stages including our multimedia experience, pre-flight briefing, and the ultimate flying experience.",
            website: "http://www.flyovercanada.com/",
            facebook: "http://www.facebook.com/flyovercanada"
        },
        {
            name: "McDonald's",
            logo: "/images/sponsors/mcdonalds.png",
            about: "Check out their website to learn more.",
            website: "https://www.mcdonalds.com/ca/en-ca.html"
        },
 
    ],
};

export default sponsors;
